# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VM4uIZZhO6EZZYfr7FGRh1LkwVBKUbzz
"""

valor = 2
valor()

